services:
  - type: web
    name: moon-xmd-v1
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: SESSION_ID
        value: ""
      - key: Prefix
        value: "."
      - key: ownerNumber
        value: "263776509966"
      - key: timezone
        value: "Africa/Harare"